import {
  boolean,
  index,
  jsonb,
  pgTable,
  text,
  timestamp,
  uuid,
  varchar,
  integer,
} from 'drizzle-orm/pg-core';

export const rawScrapedEvents = pgTable(
  'raw_scraped_events',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    sourcePlatformId: varchar('source_platform_id').notNull(),
    sourceUrl: varchar('source_url').notNull(),
    rawPayload: jsonb('raw_payload').notNull(),
    scrapedAt: timestamp('scraped_at').notNull().defaultNow(),
    normalized: boolean('normalized').notNull().default(false),
    normalizationError: text('normalization_error'),
  },
  (table) => ({
    unprocessedIdx: index('idx_raw_unprocessed').on(table.normalized),
    platformIdx: index('idx_raw_platform').on(table.sourcePlatformId),
  }),
);

export const events = pgTable(
  'events',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    slug: text('slug').unique().notNull(),
    title: text('title').notNull(),
    shortDescription: text('short_description'),
    description: text('description'),
    platform: text('platform').notNull(),
    platformEventId: text('platform_event_id'),
    sourceUrl: text('source_url').notNull(),
    bannerImage: text('banner_image'),
    thumbnailImage: text('thumbnail_image'),
    mode: text('mode'),
    category: text('category'),
    subcategory: text('subcategory'),
    startDate: timestamp('start_date', { withTimezone: true }),
    endDate: timestamp('end_date', { withTimezone: true }),
    registrationDeadline: timestamp('registration_deadline', { withTimezone: true }),
    timezone: text('timezone').default('UTC'),
    isFree: boolean('is_free').default(true),
    price: text('price'),
    location: text('location'),
    city: text('city'),
    country: text('country'),
    organizerName: text('organizer_name'),
    organizerLogo: text('organizer_logo'),
    organizerUrl: text('organizer_url'),
    tags: text('tags').array(),
    skills: text('skills').array(),
    eligibility: text('eligibility'),
    prizes: text('prizes'),
    maxTeamSize: integer('max_team_size'),
    minTeamSize: integer('min_team_size'),
    status: text('status').default('active'),
    views: integer('views').default(0),
    clicks: integer('clicks').default(0),
    bookmarks: integer('bookmarks').default(0),
    scrapedAt: timestamp('scraped_at').defaultNow(),
    updatedAt: timestamp('updated_at').defaultNow(),
    rawData: jsonb('raw_data'),
  },
  (table) => ({
    platformIdx: index('idx_events_platform').on(table.platform),
    categoryIdx: index('idx_events_category').on(table.category),
    slugIdx: index('idx_events_slug').on(table.slug),
    startDateIdx: index('idx_events_start_date').on(table.startDate),
  }),
);

export const users = pgTable(
  'users',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    googleId: varchar('google_id').notNull().unique(),
    email: varchar('email').notNull().unique(),
    isSubscribed: boolean('is_subscribed').notNull().default(false),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (table) => ({
    googleIdx: index('idx_users_google_id').on(table.googleId),
    emailIdx: index('idx_users_email').on(table.email),
  }),
);
